name: Deploy Dev environment

concurrency:
  group: deploy-${{ vars.ENVIRONMENT }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    paths:
      - '**.tf'
      - '*.tfvars'
      - '*.tfstate'
      - '*.tfstate.backup'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup: AWS Login and Terraform init'
        uses: ./.github/actions/terraform-init
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf-admin

      - name: 'Test: check and validate'
        uses: ./.github/actions/terraform-test
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf-admin

      - name: 'Deploy: to ${{ vars.ENVIRONMENT }}'
        uses: ./.github/actions/terraform-apply
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf-admin
