name: Test Terraform changes

defaults:
  run:
    working-directory: terraform

on:
  workflow_dispatch:
  push:
    paths:
      - terraform/**

env:
  ENVIRONMENT: 'dev'
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write
  contents: read

jobs:
  test-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: 'Setup: Configure AWS credentials'
        # this step adds `env.AWS_*` variables
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.TF_AWS_ROLE }}
          role-session-name: github-actions-terraform
          role-duration-seconds: 7200
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl -backend-config="key=${{ env.ENVIRONMENT }}/eks-project-pipeline/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate
