name: Test Terraform changes

# defaults:
#   run:
#     working-directory: terraform

on:
  workflow_dispatch:
  push:
    paths:
      - '**.tf' # Watches for changes to any .tf file in the root
      - '*.tfvars' # Watches for changes to any .tfvars file in the root
      - '*.tfstate' # Optional: watches for any state file changes if tracked in the repo
      - '*.tfstate.backup'
  # workflow_dispatch:
  # push:
  #   paths:
  #     - terraform/**

env:
  ENVIRONMENT: 'dev'
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write
  contents: read

jobs:
  test-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: 'Setup: Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tf-admin
          role-session-name: github-actions-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl -backend-config="key=${{ env.ENVIRONMENT }}/eks-project-pipeline/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.53.0

      - name: Terraform lint
        run: tflint -f compact
